### ISSUE TITLE
Failed to instantiate service 'core.httpRouter' for 'changelog' 

### ISSUE THREAD

**Issue by andersbackman-rf** [RSC-Labs/backstage-changelog-plugin#10]
Getting this error

```
/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1417
          throw new Error(
                ^
Error: Failed to instantiate service 'core.httpRouter' for 'changelog' because the factory function threw an error, Error: Failed to instantiate service 'core.auth' for 'changelog' because the factory function threw an error, Error: ENOENT: no such file or directory, scandir '/app/node_modules/@backstage/backend-defaults/migrations/auth'
    at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1417:17
    at async ServiceRegistry.initializeEagerServicesWithScope (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1352:11)
    at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1635:9
    at async Promise.all (index 0)
    at async #doStart (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1633:5)
    at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1562:5)
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1762:5)
Node.js v20.15.0
```

**Comment by andersbackman-rf** [comment]
backstage_backend_public_keys__keys is not created in the database, dont know if this is relevant or not

**Comment by andersbackman-rf** [comment]
resolved by replacing `"import { httpRouterServiceFactory } from '@backstage/backend-app-api';" `with `import { httpRouterServiceFactory } from '@backstage/backend-defaults/httpRouter';` in index.ts 

add installing: `yarn add --cwd packages/backend @backstage/backend-defaults`

**Comment by andersbackman-rf** [comment]
solved
